title: "A byte of Lox"
subtitle: "Changing the Web 0x0001 at a time."
author:
  name: "Federico \"Lox\" Lucignano"
  github-profile: "https://github.com/federico-lox"
  google-profile: "https://plus.google.com/+FedericoLucignano"
cache-buster: 17

