safe: true
lsi: false
pygments: false
paginate: 5
paginate_path: "page-:num"
permalink: "none"
exclude: ["Gemfile", "Gemfile.lock", "*.sublime-*", "Rakefile", "LICENSE.md",
          "TODO.md"]
title: "A byte of Lox"
subtitle: "Changing the Web 0x00000001 at a time."
author:
  name: "Federico \"Lox\" Lucignano"
  github-profile: "https://github.com/federico-lox"
  google-profile: "https://plus.google.com/+FedericoLucignano?rel=author"
url: "https://federico-lox.github.io"
cache_buster: 39
feedburner: "federico-lox"
google_analytics:
  tracking_id: "UA-42957328-2"
  page_speed_sample: 100
